spring:
  application:
    name: api-first-tutorial
server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ["configprops", "env", "health", "info", "threaddump", "logfile", "jhi-metrics", "prometheus"]